[package]
name = "farvm"
version = "1.0.0"
edition.workspace = true

[dependencies]
farvm_utils = { workspace = true }
farvm_tree = { workspace = true }
farvm_compiler = { workspace = true }
farvm_vm = { workspace = true }
